/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tabalhojava.View;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import tabalhojava.Controller.Utils;
import tabalhojava.Model.Seguidor;

/**
 *
 * @author Daniel Dória
 */
public class TelaTabela extends javax.swing.JFrame {

    /**
     * Creates new form TelaTabela
     */
    private ArrayList<Seguidor> seguidores;
    private Utils utils = new Utils();
    private DefaultTableModel modelo;
    public TelaTabela() {
        initComponents();
        this.seguidores = new ArrayList<Seguidor>();
        this.utils.inicializarSeguidores(this.seguidores);
        this.modelo = (DefaultTableModel) this.jTable1.getModel();
        popularTabela();
    }

    public ArrayList<Seguidor> getSeguidores() {
        return this.seguidores;
    }
    
    public void addSeguidor(Seguidor seguidor){
        String nome = seguidor.getNome();
        String sexo = seguidor.getSexo();
        int idade = seguidor.getIdade();
        String usuario = seguidor.getApelido();
        String dataDeInscricao = seguidor.dataToString(seguidor.getDataInscricao());
        int bits = seguidor.getBits();
        boolean isSub = seguidor.isIsSub();

        this.modelo.addRow(new Object[]{nome, sexo, idade, usuario, dataDeInscricao, bits, isSub});      
    }
    
    public void editarSeguidor(Seguidor seguidor, int index){
        String nome = seguidor.getNome();
        this.modelo.setValueAt(nome, index, 0);
        String sexo = seguidor.getSexo();
        this.modelo.setValueAt(sexo, index, 1);
        int idade = seguidor.getIdade();
        this.modelo.setValueAt(idade, index, 2);
        String usuario = seguidor.getApelido();
        this.modelo.setValueAt(usuario, index, 3);
        String dataDeInscricao = seguidor.dataToString(seguidor.getDataInscricao());
        this.modelo.setValueAt(dataDeInscricao, index, 4);
        int bits = seguidor.getBits();
        this.modelo.setValueAt(bits, index, 5);
        boolean isSub = seguidor.isIsSub();
        this.modelo.setValueAt(isSub, index, 6);     
    }
    
    
    public void popularTabela(){
        int i =  0;
        for(Seguidor seguidor: seguidores){
            String nome = seguidor.getNome();
            String sexo = seguidor.getSexo();
            int idade = seguidor.getIdade();
            String usuario = seguidor.getApelido();
            String dataDeInscricao = seguidor.dataToString(seguidor.getDataInscricao());
            int bits = seguidor.getBits();
            boolean isSub = seguidor.isIsSub();
            
            this.modelo.insertRow(i, new Object[]{nome, sexo, idade, usuario, dataDeInscricao, bits, isSub});
            
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btAdicionar = new javax.swing.JButton();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAdicionar.setText("Adicionar");
        btAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAdicionarActionPerformed(evt);
            }
        });

        btEditar.setText("Editar");
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sexo", "Idade", "Usuario", "Data de Inscrição", "Bits", "Subs"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btAdicionar)
                        .addGap(18, 18, 18)
                        .addComponent(btEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btExcluir)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAdicionar)
                    .addComponent(btEditar)
                    .addComponent(btExcluir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAdicionarActionPerformed
        // TODO add your handling code here:
        if(!seguidores.isEmpty()){
            System.out.print(seguidores.get(0).getApelido());
        }
        TelaAddSeguidor telaAdd = new TelaAddSeguidor(this);
        telaAdd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btAdicionarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        
        int resposta = JOptionPane.showConfirmDialog(
                null, 
                "Quer mesmo deletar essa pessoa?", 
                "Excluir usuário",
                JOptionPane.YES_NO_OPTION
        );
        
        if(resposta == 1){
            return;
        }
        
        int linhaSelecionada = this.jTable1.getSelectedRow();
        if(linhaSelecionada == -1){
            utils.mostrarErro("Nenhum seguidor selecionado");
            
            return;
        }
        
        String apelido = this.jTable1.getModel().getValueAt(linhaSelecionada, 3).toString();
        int i;
        for(i =0; i<this.seguidores.size(); i++){
            Seguidor seguidor = this.seguidores.get(i);
            if(seguidor.getApelido().equals(apelido)){
                break;
            }
        }
        if(i==this.seguidores.size()){
            this.utils.mostrarErro("O usuário selecionado não existe.");
            
            return;
        }
        this.seguidores.remove(i);
        this.modelo.removeRow(linhaSelecionada);
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = this.jTable1.getSelectedRow();
        if(linhaSelecionada == -1){
            utils.mostrarErro("Nenhum seguidor selecionado");
            
            return;
        }
        
        String apelido = this.jTable1.getModel().getValueAt(linhaSelecionada, 3).toString();
        int i;
        for(i =0; i<this.seguidores.size(); i++){
            Seguidor seguidor = this.seguidores.get(i);
            if(seguidor.getApelido().equals(apelido)){
                break;
            }
        }
        if(i==this.seguidores.size()){
            this.utils.mostrarErro("O usuário selecionado não existe.");
            
            return;
        }
        TelaAddSeguidor addSeguidor = new TelaAddSeguidor(i, linhaSelecionada, this);
        addSeguidor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdicionar;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
