/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tabalhojava.View;

import java.util.ArrayList;
import java.util.Set;

import tabalhojava.Controller.Utils;
import tabalhojava.Model.Seguidor;

/**
 *
 * @author Daniel Dória
 */
public class TelaAddSeguidor extends javax.swing.JFrame {
    
    private TelaTabela telaTabela;
    private Utils utils = new Utils();
    private Seguidor seguidor = new Seguidor();
    private boolean isEditando = false;
    private int index = -1;
    private int linhaTabela = -1;
    /**
     * Creates new form TelaAddSeguidor
     */
    public TelaAddSeguidor(TelaTabela telaTabela) {
        inicializar(telaTabela);
    }
    
    private void inicializar(TelaTabela telaTabela){
        initComponents();
        this.telaTabela = telaTabela;
        this.buttonGroup1.add(this.btFem);
        this.buttonGroup1.add(this.btMas);
        this.buttonGroup1.add(this.btNb);
    }
    public TelaAddSeguidor(int index, int linhaTabela, TelaTabela telaTabela){
        inicializar(telaTabela);
        this.index = index;
        this.isEditando = true;
        this.linhaTabela = linhaTabela;
        carregarSeguidor();
    }
    
    private void carregarSeguidor(){
        Seguidor seguidor = this.telaTabela.getSeguidores().get(this.index);
        this.txtNome.setText(seguidor.getNome());
        this.txtUsuario.setText(seguidor.getApelido());
        this.txtNascimento.setText(seguidor.dataToString(seguidor.getNascimento()));
        this.txtInsc.setText(seguidor.dataToString(seguidor.getDataInscricao()));
        this.txtIdade.setText(seguidor.getIdade()+"");
        this.bitsSpinner.setValue(seguidor.getBits());
        this.inscritoCheckBox.setSelected(seguidor.isIsSub());
        switch(seguidor.getSexo()){
            case "F": 
                this.btFem.setSelected(true);
                break;
            case "M":
                 this.btMas.setSelected(true);
                 break;
            default:
                this.btNb.setSelected(true);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNascimento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIdade = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtInsc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bitsSpinner = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        inscritoCheckBox = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        btFem = new javax.swing.JRadioButton();
        btMas = new javax.swing.JRadioButton();
        btNb = new javax.swing.JRadioButton();
        btSalvar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nome:");

        jLabel2.setText("Usuário:");

        jLabel3.setText("Date de nascimento:");

        txtNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNascimentoActionPerformed(evt);
            }
        });

        jLabel4.setText("Idade:");

        txtIdade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtIdade.setText("00");

        jLabel5.setText("Data de Inscrição:");

        jLabel6.setText("Bits:");

        inscritoCheckBox.setText("Inscrito");
        inscritoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inscritoCheckBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Sexo:");

        btFem.setText("Feminino");

        btMas.setText("Masculino");

        btNb.setText("Não binário");

        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNome)
                    .addComponent(txtUsuario)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bitsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(inscritoCheckBox))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(txtIdade)))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(txtInsc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btFem)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btSalvar)
                                        .addGap(90, 90, 90)
                                        .addComponent(btCancelar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btMas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btNb)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdade)
                    .addComponent(txtInsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bitsSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inscritoCheckBox))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFem)
                    .addComponent(btMas)
                    .addComponent(btNb))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btCancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inscritoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inscritoCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inscritoCheckBoxActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        try{
            if(this.txtNome.getText().length()<2){
                this.utils.mostrarErro("Nome inválido!");
            }
            this.seguidor.setNome(this.txtNome.getText());
            boolean isValido = this.seguidor.validarApelido(this.txtUsuario.getText());

            if(!isValido){
                this.utils.mostrarErro("Usuáio inválido");
                return;
            }
            boolean isUnico = this.seguidor.validarApelido(this.txtUsuario.getText(), this.telaTabela.getSeguidores());
            if(!this.isEditando && !isUnico){
                this.utils.mostrarErro("Usuáio já existe");
                return;
            }
      
            this.seguidor.setApelido(this.txtUsuario.getText());
            this.seguidor.setNascimento(txtNascimento.getText());

            boolean isSub = this.inscritoCheckBox.isSelected();
            this.seguidor.setIsSub(isSub);
            this.seguidor.setDataInscricao(this.txtInsc.getText());
            int bits = (Integer) this.bitsSpinner.getValue();
            this.seguidor.setBits(bits);
            
            if(this.btMas.isSelected()){
                this.seguidor.setSexo("M");
            } else if(this.btFem.isSelected()){
                this.seguidor.setSexo("F");
            } else{
                this.seguidor.setSexo("NB");
            }
            if(this.isEditando){
                this.telaTabela.getSeguidores().set(index, seguidor);
                this.telaTabela.editarSeguidor(this.seguidor, linhaTabela);
            }else{
                this.telaTabela.getSeguidores().add(this.seguidor);
                this.telaTabela.addSeguidor(this.seguidor);
            }  
            
            this.telaTabela.setVisible(true);
            this.dispose();
        }catch(Exception e){
            this.utils.mostrarErro(e.getMessage());
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void txtNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNascimentoActionPerformed
        // TODO add your handling code here:
        try{
            int idade = this.seguidor.calcularIdade(this.txtNascimento.getText());
            this.txtIdade.setText(idade+"");
        }catch(Exception e){
            this.utils.mostrarErro(e.getMessage());
        }
    }//GEN-LAST:event_txtNascimentoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        // TODO add your handling code here:
        this.telaTabela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner bitsSpinner;
    private javax.swing.JButton btCancelar;
    private javax.swing.JRadioButton btFem;
    private javax.swing.JRadioButton btMas;
    private javax.swing.JRadioButton btNb;
    private javax.swing.JButton btSalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox inscritoCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtIdade;
    private javax.swing.JTextField txtInsc;
    private javax.swing.JTextField txtNascimento;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
